### ISSUE TITLE
Upgrade the kube-rbac-proxy to v0.14.1 to mitigate security vulnerabilities

### ISSUE THREAD

**Issue by FushuWang** [streamnative/pulsar-resources-operator#106]
There are some security vulnerabilities in the security report of artifacthub. https://artifacthub.io/packages/helm/streamnative/pulsar-resources-operator?modal=security-report&image=docker.cloudsmith.io%2Fstreamnative%2Foperators%2Fpulsar-resources-operator%3Av0.3.2&target=docker.cloudsmith.io%2Fstreamnative%2Foperators%2Fpulsar-resources-operator%3Av0.3.2%20(debian%2011.7)

And the customer would worry about the security thread.

**Comment by muni-chada** [comment]
following
