### ISSUE TITLE
PulsarTopic cannot be deleted: already deleted

### ISSUE THREAD

**Issue by tomjo** [streamnative/pulsar-resources-operator#114]
When deleting a PulsarTopic with policy CleanUpAfterDeletion sometimes the resource gets stuck. The operator will log: "error":"code: 404 reason: Topic not exist".

The reason is that during the reconciliation loop the topic is deleted but removing the finalizer fails due to `"Operation cannot be fulfilled on pulsartopics.resource.streamnative.io \"xxx\": the object has been modified; please apply your changes to the latest version and try again"`, on the next reconciliation loop it will first try to delete the topic again which fails since it is already deleted.

We're using argocd in our environment and maybe this is updating the resource somehow, we're still investigating this part. But perhaps it makes sense for the deletion of a topic to not fail if it is already deleted. Since this could also happen if the request to delete the finalizer times out due to a network hickup or something else.

The same behavior probably exists for the other resources as well.

**Comment by FushuWang** [comment]
@tomjo Thanks for your report. We will consider this issue
