### ISSUE TITLE
[Bug] - Topic creation fails

### ISSUE THREAD

**Issue by david-streamlio** [streamnative/pulsar-resources-operator#121]
When I apply the attached config, I can verify that the tenant and namespace are created, but the topic is not.

Steps to reproduce:
1. Create a Pulsar cluster inside the K8s namespace `pulsar` using the Pulsar-operator 
2. kubectl apply -f 03-resources-quick-start.yaml

Validation:
1. `kubectl exec -it -n pulsar pod/brokers-broker-0 /pulsar/bin/pulsar-admin tenants list`, see `foo` returned
2. `kubectl exec -it -n pulsar pod/brokers-broker-0 /pulsar/bin/pulsar-admin namespaces list foo`, see `foo/bar` returned
3. `kubectl exec -it pod/brokers-broker-0 -n pulsar /pulsar/bin/pulsar-admin topics list-partitioned-topics foo/bar`, see nothing returned

Expected output:
foo/bar/topic123

[03-resources-quick-start.zip](https://github.com/streamnative/pulsar-resources-operator/files/11991337/03-resources-quick-start.zip)

**Comment by ericsyh** [comment]
@david-streamlio for this kind of issue, usually you can get root cause from the operator log:

```
{"severity":"error","timestamp":"2023-08-07T11:07:17Z","logger":"controller.pulsarconnection","message":"Reconciler error","reconciler group":"resource.streamnative.io","reconciler kind":"PulsarConnection","name":"pulsar-connection","namespace":"snp","error":"reconcile namespace [code: 412 reason: Backlog Quota exceeds configured retention quota for namespace. Please increase retention quota and retry]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
```
