### ISSUE TITLE
Support the customized namespace for the secret of PulsarConnection Authentication

### ISSUE THREAD

**Issue by FushuWang** [streamnative/pulsar-resources-operator#17]
For now, the authentication of `PulsarConnection` requires a secret that only can be accessed in the same namespace of the `PulsarConnection` cr. It should be configurable, the default namespace is the namespace of `PulsarConnection`

**Comment by marekczajkowski** [comment]
Hi I think it should be possible to provide secret's namespace. I have another operator that creates pulsar connection and adds ownerReference so it's gone when parent resource is removed. When Im forced to create PulsarConnection in the same namespace where secret's are hold it can not add owner reference when dependent resource is in different namespace.
