### ISSUE TITLE
How to understand what is going wrong with the deployment of the PulsarConnection/PulsarTopic

### ISSUE THREAD

**Issue by mehmetsalgar** [streamnative/pulsar-resources-operator#65]
Hi,

I am experimenting with 'pulsar-resources-operator' to create Topics in my Pulsar Cluster created with Pulsar Operator.

My Pulsar cluster is working and I can create Topics with 'pulsar-admin' from Pulsar Brokers Pods shell....

Now if I install 'pulsar-resources-operator' to the same name space I installed the Pulsar-Operator 'pulsar-system', the operator Pod start happily without any error warnings in the logs.

{"severity":"info","timestamp":"2022-10-24T07:59:18Z","message":"Starting server","kind":"health probe","addr":"[::]:8081"}
I1024 07:59:18.104575       1 leaderelection.go:248] attempting to acquire leader lease ms/feaa54b6.streamnative.io...
I1024 07:59:18.122522       1 leaderelection.go:258] successfully acquired lease ms/feaa54b6.streamnative.io
{"severity":"info","timestamp":"2022-10-24T07:59:18Z","logger":"controller.pulsarconnection","message":"Starting EventSource","reconciler group":"resource.streamnative.io","reconciler kind":"PulsarConnection","source":"kind source: *v1alpha1.PulsarConnection"}
{"severity":"info","timestamp":"2022-10-24T07:59:18Z","logger":"controller.pulsarconnection","message":"Starting EventSource","reconciler group":"resource.streamnative.io","reconciler kind":"PulsarConnection","source":"kind source: *v1alpha1.PulsarTenant"}
{"severity":"info","timestamp":"2022-10-24T07:59:18Z","logger":"controller.pulsarconnection","message":"Starting EventSource","reconciler group":"resource.streamnative.io","reconciler kind":"PulsarConnection","source":"kind source: *v1alpha1.PulsarNamespace"}
{"severity":"info","timestamp":"2022-10-24T07:59:18Z","logger":"controller.pulsarconnection","message":"Starting EventSource","reconciler group":"resource.streamnative.io","reconciler kind":"PulsarConnection","source":"kind source: *v1alpha1.PulsarTopic"}
{"severity":"info","timestamp":"2022-10-24T07:59:18Z","logger":"controller.pulsarconnection","message":"Starting EventSource","reconciler group":"resource.streamnative.io","reconciler kind":"PulsarConnection","source":"kind source: *v1alpha1.PulsarPermission"}
{"severity":"info","timestamp":"2022-10-24T07:59:18Z","logger":"controller.pulsarconnection","message":"Starting Controller","reconciler group":"resource.streamnative.io","reconciler kind":"PulsarConnection"}
{"severity":"info","timestamp":"2022-10-24T07:59:18Z","logger":"controller.pulsarconnection","message":"Starting workers","reconciler group":"resource.streamnative.io","reconciler kind":"PulsarConnection","worker count":1}

And if I deploy my PulsarConnection and PulsarTopic to the 'test' Namespace as it described in Tutorial, I don't get any reaction from the operator, no errors, no success messages and my Topic is not generated.

This is how my PulsarConnection looks like

`
    apiVersion: pulsar.streamnative.io/v1alpha1
    kind: PulsarConnection
    metadata:
      name: {{ .Release.Namespace }}-pulsar-connection
      namespace: {{ .Release.Namespace }}
    spec:
      adminServiceURL: "http://pulsar-broker.test.svc.cluster.local:8080"
`

I can see the PulsarConnection resource in my kubernetes environment but what irritates me...

OBSERVED_GENERATION is empty, along with ADMIN_SERVICE_URL, but as you can see I have value in 'adminServiceURL'...

It either 'pulsar-resources-operator' does not recognise an new Resource is deployed or it gets no connection to Pulsar cluster but I do not see any errors in any pods logs...

So is there a way to increase log levels for the 'pulsar-resources-operator' logs or how can I diagnose what is going wrong

**Comment by FushuWang** [comment]
Hi @mehmetsalgar, thanks for the feedback. It's the doc's issue. Could you replace the apiVersion with `resource.streamnative.io/v1alpha1`.  I have fixed the apiVersion issue in this [PR](https://github.com/streamnative/pulsar-resources-operator/pull/64).

```yaml
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarConnection
metadata:
  name: "test-pulsar-connection"
  namespace: ok
spec:
  adminServiceURL: http://o-sn-platform-broker.ok.svc.cluster.local:8080
  authentication:
    token:
      secretRef:
        name: o-sn-platform-vault-secret-env-injection
        key: brokerClientAuthenticationParameters
```

**Comment by FushuWang** [comment]
But no matter which apiVersion it is, if the manifest is correct, the `ADMIN_SERVICE_URL` shouldn't be empty. The empty `OBSERVED_GENERATION` is okay at the first time.

**Comment by FushuWang** [comment]
There is also another point you should know. Please use `pulsarconnection.resource.streamnative.io` when you run kubectl command to get it.
